//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrizDeSeguimiento.Models.Modelsfromdatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class hist_financista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hist_financista()
        {
            this.hist_relacion_op_finan = new HashSet<hist_relacion_op_finan>();
        }
    
        public int añomescierre { get; set; }
        public int id_financista { get; set; }
        public int Id_tipo { get; set; }
        public string nombre_financista { get; set; }
    
        public virtual hist_tipo_financista hist_tipo_financista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hist_relacion_op_finan> hist_relacion_op_finan { get; set; }
    }
}
