//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrizDeSeguimiento.Models.Modelsfromdatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class hist_iniciativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hist_iniciativa()
        {
            this.hist_oportunidad = new HashSet<hist_oportunidad>();
        }
    
        public int añomescierre { get; set; }
        public int id_iniciativa { get; set; }
        public string nombre_iniciativa { get; set; }
        public int linea_id_linea { get; set; }
    
        public virtual hist_linea hist_linea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hist_oportunidad> hist_oportunidad { get; set; }
    }
}
