//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrizDeSeguimiento.Models.Modelsfromdatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrizSeguimiento
    {
        public string Area { get; set; }
        public string Linea { get; set; }
        public string Iniciativa { get; set; }
        public string Oportunidad { get; set; }
        public string Financista { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
        public string FechaEntregaPropuesta { get; set; }
        public string FechaAdjudicacionPropuesta { get; set; }
        public decimal Ingreso { get; set; }
        public decimal GastoHH { get; set; }
        public decimal GastoOP { get; set; }
        public decimal Margen { get; set; }
        public decimal IngresoSig { get; set; }
        public decimal GastoHHSig { get; set; }
        public decimal GastoOPSig { get; set; }
        public decimal MargenSig { get; set; }
        public decimal IngresoSubS { get; set; }
        public decimal GastoHHSubS { get; set; }
        public decimal GastoOPSubS { get; set; }
        public decimal MargenSubS { get; set; }
        public string Codigo { get; set; }
        public string Comentario { get; set; }
    }
}
